declare const allowedAlbums: {
    "base gallery": string;
    "Pascal, Flo, and Timbits visit Halifax": string;
    "Ian and Diana's cottage in New Brunswick": string;
    "Steve and Kristen visit Halifax": string;
    "Okta IAM Design Offsite": string;
    "Okta IAM Design Offsite - Auth0 photos": string;
    "Bryan and Molly visit Halifax": string;
    "Ronnie visits Halifax": string;
    "Okta Assemble 23 in Mexico": string;
    "Big January Snowfall": string;
    "High Head Trail in Prospect, NS": string;
    "Halifax Oyster Festival": string;
    "Sailing and Hot Pot": string;
    "Halloween 2022": string;
    "Hurricane Fiona": string;
    "Mark McCabe visits Halifax": string;
    "Kanata Day 2022 in Halifax": string;
    "Peggy's Cove and Robin's trip to Halifax": string;
    "Dartmouth Cherry Blossoms": string;
    "Moving to Halifax": string;
    "Ma Goodbye": string;
    "Lily Turns Two": string;
    "James and Krishna": string;
    "Weekend at Phil and Nikki's": string;
    "Algonquin Camping 2021": string;
    "Shelbie, Ryan, Holly, and Friends": string;
    "Scouting Halifax August 2021": string;
    "Bruce Trail - Family Day": string;
    "Mono Cliffs Park": string;
    "Lake Superior 2020": string;
    "Lily - 2020/09/26": string;
    Essaouira: string;
    Casablanca: string;
    Tangier: string;
    Chefchouen: string;
    Fes: string;
    "Desert Tour": string;
    Marrakesh: string;
    "Lilith Robin Wylie Freake": string;
    "Pivotal X Curling": string;
    "Jordyn's 10th Birthday": string;
    "Concourse at Kinka Izakaya": string;
    "Pereira Christmas 2019": string;
    "Julia & Aodhan's Baby Shower": string;
    "Connell's 16th Birthday Party": string;
    "Spring One Platform 2019": string;
    "Tobermory and Cyprus Lake Camping": string;
    "Pivotal Beach Day 2019": string;
    "Pivotal Island 2019": string;
    "Canada Day 2019": string;
    "Montreal w Shelbie and Ryan": string;
    "Desjardins Montreal": string;
    "San Francisco 2019": string;
    "CF Summit Philadelphia 2019": string;
    "Pivotal at Archer's Arena": string;
    "Shelbie and Ryan's birthday": string;
    "Jordyn's 9th Birthday 2019": string;
    "Pereira Christmas 2018": string;
    "Cura\u00E7ao 2018": string;
    "Justin's Birthday 2018": string;
    "Yasmin's Baby Mikael": string;
    "Julia and Aodhan's Wedding": string;
    "Fake Boos, Halloween 2018": string;
    "Matthew and Alex's Wedding BW": string;
    "Matthew and Alex's Wedding": string;
    "Julia and Aodhan": string;
    "Cottaging 2018-08-03": string;
    "Statflo Barbecue": string;
    "Wells Hill Park": string;
    "Lizfest 2018": string;
    "Trinity Bellwoods with Friendsday friends": string;
    "AB BC Road Trip 2018": string;
    "Wes and Morgan and the kids at Trinity Bellwoods": string;
    "Statflo Product Offsite 2018": string;
    "Friendsday Farewell Barbecue": string;
    "Pereira Easter 2018": string;
    "Mom's Birthday 2018": string;
    "Statflo Potluck 2018": string;
    "Augusta and Olive'": string;
    "iQmetrix Winnipeg 2018": string;
    "Delayed New Years at Shelbie and Ryan's": string;
    "Pereira Christmas 2017": string;
    "Jordyn's 8th Birthday 2018": string;
    "Phil's Super Soft Birthday": string;
    "Statflo at Rec Room": string;
    "Darya's Statflo Goodbye": string;
    "Justin's birthday 2017": string;
    "Games night at Jordan and Nicole's": string;
    "Ottawa New Years 2018": string;
    "Statflo at BATL": string;
    "Halloween at Wes and Morgan's 2017": string;
    "Halloween 2017": string;
    "Iceland 2017": string;
    "Belleville 2017": string;
    "Robin's Birthday 2017": string;
    "Celeste at Trillium Park": string;
    "The Fix Ice Cream Shop": string;
    "Statflo Barbecue 2017": string;
    "Wes Kait Chris Jasper Augusta Jacob": string;
    "August Long Weekend 2017": string;
    "Canada Day with Jess and Alex": string;
    "Pie day at Statflo": string;
    "St Lucia": string;
    "Pereira Christmas 2016": string;
    "Statflo Christmas Party 2016": string;
    "Halloween 2016 at Wes and Morgan's": string;
    "Spook Me Like One of Your French Girls (Halloween 2016)": string;
    "Statflo at Mengrai": string;
    "August Long Weekend at the Cottage 2016": string;
    "Labour Day 2016 at the Cottage": string;
    "Dad's Birthday 2016-09-25": string;
    "Statflo Goodbye Lunch": string;
    "Friendsday Trinity Bellwoods": string;
    "Jasper's 2nd Birthday": string;
    "Julia's Cats": string;
    "OneEleven Boat Cruise": string;
    "Jasper and Olive": string;
    "Toronto Island with Celeste": string;
    "Barbecue at Brian and Melody's": string;
    "Celeste's Grad Party": string;
    "Owen at Statflo": string;
    "Wine Tasting trip with Phil and Nikky": string;
    "Matt and Celeste at Dave's Birthday": string;
    "Holiday Pictures": string;
    "Kait and Chris' wedding": string;
    "Flea Market": string;
    "Labour day at Hanlan's Point": string;
    "Sandbanks with Nikky and Phil": string;
    "Austra and Tribe Called Red": string;
    "Barbecue at Wes and Morgan's": string;
    "Celeste and Matthew go to Paris": string;
    "Belleville Trip": string;
    "Toronto Global Game Jam 2015": string;
    "Jasper's first birthday 2015": string;
    "Christina and Laura's birthday": string;
    "Shelbie's 30th Birthday": string;
    "Badlands with Nicole": string;
    "Innisfil 2014": string;
    "Robin's Dirty 30": string;
    "Matthew Manna's 30th Birthday": string;
    "Friendsday Go Karting": string;
    "Friendsday Ribsday": string;
    "Pancake Party at Nicole's": string;
    "Nicole's 30th Birthday": string;
    "Sohn at the Horseshoe": string;
    "Flip Cup Friday": string;
    "Festive Friendsday": string;
    "Board Games at Wes and Morgan's": string;
    "Shelbie and Ryan's Birthday Bash": string;
    "Jasper's baby photos": string;
    "Innisfil 2013": string;
    "Nicole's Farewell to the 20s": string;
    "Wes and Morgan's baby shower": string;
    "OCAD beach party": string;
    "Dinner at Wes and Morgan's": string;
    "Melody and Brian's barbecue": string;
    "Barbecue at Morgan and Wesley's - 2013-05-29": string;
    "Rooftop Barbecue at Brian and Melody's": string;
    "Cadillacs and Cadavers at Stones Place": string;
    "May 2013 Snapshots": string;
    "Easter 2013": string;
    "Bethlehem, Jerusalem, March 2013": string;
    "Bethlehem, March 2013": string;
    "Nazareth, Cana, Mount of the Precipice, River Jordan, March 2013": string;
    "Tiberius, Lake Galilee, March 2013": string;
    "Board Games, Jan 2013": string;
    "Jordyn's Birthday 2013": string;
    "Hockey in Whitby, Jan 2013": string;
    "New Year's 2012": string;
    "Pereira Christmas 2012": string;
    "Matthew's 29th Birthday, 2012": string;
    "Connell's 9th Birthday October 2012": string;
    "Thanksgiving 2012": string;
    "Brayden's 6th Birthday August 2012": string;
    "Uncle Peter in England 2012": string;
    "Grandma's 90th Birthday 2012": string;
    "Mother's Day 2012": string;
    "Easter 2012 - Dad's Pictures": string;
    "Easter 2012": string;
    "Mom's Birthday 2012": string;
    "Mom's 65th Birthday 2012": string;
    "Christmas 2011": string;
    "Jessica's homecoming - September 2011": string;
    "Paella Party 2011": string;
    "Connell's 8th Birhday 2011": string;
    "Uncle Peter's Birthday 2011": string;
    "Dad's birthday 2011": string;
    "Labour Day 2011": string;
    "Angela and Jonathan's Wedding 2011": string;
    "Angela and Jonathan pre-Wedding 2011": string;
    "Quick visit to Jenn's - August 2011": string;
    "Toronto Island Picnic": string;
    "July Long Weekend 2011": string;
    "Father's Day 2011": string;
    "Easter 2011": string;
    "Connell's First Communion": string;
    "Mom's Birthday 2011": string;
    "Pizza Party 2011": string;
    "Jordyn's 1st Birthday 2011": string;
    "Steve's Thailand Trip": string;
    "Jessica's Going Away Party": string;
    "Christmas in London 2010": string;
    "Jessica and Alex's Wedding": string;
    "Thanksgiving 2010": string;
    "Samson and Delilah Katz": string;
    "Grandma's 85th Birthday 2": string;
    "Grandma's Birthday 2010": string;
    "Cottage September 3 2010": string;
    "Dad's Birthday September 2010": string;
    "Steve's Birthday 2010": string;
    "Easter 2010": string;
    "Mom's Birthday 6x8 Portraits": string;
    "Jordyn at 1 Month": string;
    "Grandma's 85th Birthday": string;
    "Connell and Brayden Cellphone Pics 2008": string;
    "Brayden's Christening": string;
    "July 1st Cottage Weekend": string;
    "Trampolines at the Cottage 2006": string;
    "Steve's 25th Birthday 2006": string;
    "Steve's 25th Birthday 2006 II": string;
    "Connell's 5th Birthday": string;
    "Dominican Republic 2003": string;
    "Jennifer and Kevin's Wedding": string;
    "Dave's Birthday": string;
    "Ryan's Singalong Birthday": string;
    "Shelbie Vermette's Birthday at Hacienda": string;
    "Halloween (not a thinly veiled occult gathering)": string;
    "Jasper Tocker's 2nd Birthday": string;
};
export default allowedAlbums;
